version: "3.7"
services:
   prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheus-data:/prometheus
     ports:
       - "9090:9090"

   grafana:
     image: grafana/grafana:latest
     ports:
       - "3000:3000"
     volumes:
       - graphana-data:/var/lib/grafana
     links:
       - prometheus

volumes:
   prometheus-data:
   graphana-data:

    
